providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install",
  "npm --prefix backend install"
]

[phases.build]
cmds = []

[start]
cmd = "npm --prefix backend run start"

